name: Build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest


        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Cypress run
            uses: cypress-io/github-action@v2
            with:
              build: npm run build
              start: npm start
          - name: Jest run
            run: npm test






